spring.application.name=email-writer

#gemini.api.url =${GEMINI_API_URL}
#gemini.api.key=${GEMINI_API_KEY}

gemini.api.url =https://generativelanguage.googleapis.com
#gemini.api.key = {adsffdsgfdgdvgfdgfgfdgfd} - Dummy 
#Generate your api key and insert it in dummy .



